# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(620, 579)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.configurationFrame = QtWidgets.QFrame(self.centralwidget)
        self.configurationFrame.setGeometry(QtCore.QRect(10, 10, 601, 120))
        self.configurationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.configurationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.configurationFrame.setObjectName("configurationFrame")
        self.layoutWidget_2 = QtWidgets.QWidget(self.configurationFrame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 601, 120))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.configuration = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.configuration.setContentsMargins(0, 0, 0, 0)
        self.configuration.setObjectName("configuration")
        self.titleLayout = QtWidgets.QVBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.title = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.titleLayout.addWidget(self.title)
        self.titleLine = QtWidgets.QFrame(self.layoutWidget_2)
        self.titleLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.titleLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.titleLine.setObjectName("titleLine")
        self.titleLayout.addWidget(self.titleLine)
        self.configuration.addLayout(self.titleLayout)
        self.separatorLayout = QtWidgets.QHBoxLayout()
        self.separatorLayout.setObjectName("separatorLayout")
        self.separatorLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.separatorLabel.setObjectName("separatorLabel")
        self.separatorLayout.addWidget(self.separatorLabel)
        self.separatorEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.separatorEdit.setObjectName("separatorEdit")
        self.separatorLayout.addWidget(self.separatorEdit)
        self.separatorDefaultLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.separatorDefaultLabel.setObjectName("separatorDefaultLabel")
        self.separatorLayout.addWidget(self.separatorDefaultLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.separatorLayout.addItem(spacerItem)
        self.configuration.addLayout(self.separatorLayout)
        self.lineTerminatorLayout = QtWidgets.QHBoxLayout()
        self.lineTerminatorLayout.setObjectName("lineTerminatorLayout")
        self.lineTerminatorLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.lineTerminatorLabel.setObjectName("lineTerminatorLabel")
        self.lineTerminatorLayout.addWidget(self.lineTerminatorLabel)
        self.lineTerminatorEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineTerminatorEdit.setObjectName("lineTerminatorEdit")
        self.lineTerminatorLayout.addWidget(self.lineTerminatorEdit)
        self.lineTerminatorDefaultLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.lineTerminatorDefaultLabel.setObjectName("lineTerminatorDefaultLabel")
        self.lineTerminatorLayout.addWidget(self.lineTerminatorDefaultLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lineTerminatorLayout.addItem(spacerItem1)
        self.configuration.addLayout(self.lineTerminatorLayout)
        self.testPercentajeLayout = QtWidgets.QHBoxLayout()
        self.testPercentajeLayout.setObjectName("testPercentajeLayout")
        self.testPerLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.testPerLabel.setObjectName("testPerLabel")
        self.testPercentajeLayout.addWidget(self.testPerLabel)
        self.testPerEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.testPerEdit.setObjectName("testPerEdit")
        self.testPercentajeLayout.addWidget(self.testPerEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.testPercentajeLayout.addItem(spacerItem2)
        self.configuration.addLayout(self.testPercentajeLayout)
        self.debugTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.debugTextBrowser.setGeometry(QtCore.QRect(10, 390, 599, 181))
        self.debugTextBrowser.setObjectName("debugTextBrowser")
        self.fileBrowserFrame = QtWidgets.QFrame(self.centralwidget)
        self.fileBrowserFrame.setGeometry(QtCore.QRect(10, 170, 601, 65))
        self.fileBrowserFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fileBrowserFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fileBrowserFrame.setObjectName("fileBrowserFrame")
        self.layoutWidget = QtWidgets.QWidget(self.fileBrowserFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 601, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.fileBrowserLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.fileBrowserLayout.setContentsMargins(0, 0, 0, 0)
        self.fileBrowserLayout.setObjectName("fileBrowserLayout")
        self.title_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title_2.setFont(font)
        self.title_2.setObjectName("title_2")
        self.fileBrowserLayout.addWidget(self.title_2)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.fileBrowserLayout.addWidget(self.line)
        self.fileBrowserLayoutH = QtWidgets.QHBoxLayout()
        self.fileBrowserLayoutH.setObjectName("fileBrowserLayoutH")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.fileBrowserLayoutH.addWidget(self.label_2)
        self.trainingLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.trainingLineEdit.setEnabled(False)
        self.trainingLineEdit.setAcceptDrops(False)
        self.trainingLineEdit.setObjectName("trainingLineEdit")
        self.fileBrowserLayoutH.addWidget(self.trainingLineEdit)
        self.browseButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseButton.sizePolicy().hasHeightForWidth())
        self.browseButton.setSizePolicy(sizePolicy)
        self.browseButton.setObjectName("browseButton")
        self.fileBrowserLayoutH.addWidget(self.browseButton)
        self.fileBrowserLayout.addLayout(self.fileBrowserLayoutH)
        self.thresholdFrame = QtWidgets.QFrame(self.centralwidget)
        self.thresholdFrame.setGeometry(QtCore.QRect(10, 240, 601, 71))
        self.thresholdFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.thresholdFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.thresholdFrame.setObjectName("thresholdFrame")
        self.layoutWidget1 = QtWidgets.QWidget(self.thresholdFrame)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 601, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.thresholdLayout = QtWidgets.QHBoxLayout()
        self.thresholdLayout.setObjectName("thresholdLayout")
        self.thresholdLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.thresholdLabel.setObjectName("thresholdLabel")
        self.thresholdLayout.addWidget(self.thresholdLabel)
        self.thresholdEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.thresholdEdit.setObjectName("thresholdEdit")
        self.thresholdLayout.addWidget(self.thresholdEdit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.thresholdLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.thresholdLayout)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gainRadioButton = QtWidgets.QRadioButton(self.layoutWidget1)
        self.gainRadioButton.setObjectName("gainRadioButton")
        self.horizontalLayout_3.addWidget(self.gainRadioButton)
        self.gainRatioRadioButton = QtWidgets.QRadioButton(self.layoutWidget1)
        self.gainRatioRadioButton.setObjectName("gainRatioRadioButton")
        self.horizontalLayout_3.addWidget(self.gainRatioRadioButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 140, 601, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.confirmButtonLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.confirmButtonLayout.setContentsMargins(0, 0, 0, 0)
        self.confirmButtonLayout.setObjectName("confirmButtonLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.confirmButtonLayout.addItem(spacerItem5)
        self.confirmButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.confirmButton.setObjectName("confirmButton")
        self.confirmButtonLayout.addWidget(self.confirmButton)
        self.discardButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.discardButton.setObjectName("discardButton")
        self.confirmButtonLayout.addWidget(self.discardButton)
        self.buildTreeFrame = QtWidgets.QFrame(self.centralwidget)
        self.buildTreeFrame.setGeometry(QtCore.QRect(10, 320, 601, 25))
        self.buildTreeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buildTreeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buildTreeFrame.setObjectName("buildTreeFrame")
        self.layoutWidget3 = QtWidgets.QWidget(self.buildTreeFrame)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 601, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.buildTreeButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.buildTreeButton.setEnabled(True)
        self.buildTreeButton.setObjectName("buildTreeButton")
        self.horizontalLayout.addWidget(self.buildTreeButton)
        self.treeOptionsFrame = QtWidgets.QFrame(self.centralwidget)
        self.treeOptionsFrame.setGeometry(QtCore.QRect(10, 350, 601, 25))
        self.treeOptionsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.treeOptionsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.treeOptionsFrame.setObjectName("treeOptionsFrame")
        self.layoutWidget4 = QtWidgets.QWidget(self.treeOptionsFrame)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 0, 601, 25))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.classificationButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.classificationButton.setToolTip("")
        self.classificationButton.setObjectName("classificationButton")
        self.horizontalLayout_2.addWidget(self.classificationButton)
        self.plotTreeButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.plotTreeButton.setObjectName("plotTreeButton")
        self.horizontalLayout_2.addWidget(self.plotTreeButton)
        self.plotDataButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.plotDataButton.setObjectName("plotDataButton")
        self.horizontalLayout_2.addWidget(self.plotDataButton)
        self.configurationFrame.raise_()
        self.debugTextBrowser.raise_()
        self.fileBrowserFrame.raise_()
        self.thresholdFrame.raise_()
        self.buildTreeFrame.raise_()
        self.treeOptionsFrame.raise_()
        self.layoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Importación"))
        self.separatorLabel.setText(_translate("MainWindow", "Separador de campos:"))
        self.separatorDefaultLabel.setText(_translate("MainWindow", "(por defecto \',\')"))
        self.lineTerminatorLabel.setText(_translate("MainWindow", "Delimitador de fila:"))
        self.lineTerminatorDefaultLabel.setText(_translate("MainWindow", "(por defecto \'salto de línea\')"))
        self.testPerLabel.setText(_translate("MainWindow", "Porcentaje de datos para prueba:"))
        self.title_2.setText(_translate("MainWindow", "Paramétros del modelo"))
        self.label_2.setText(_translate("MainWindow", "Archivo:"))
        self.browseButton.setText(_translate("MainWindow", "Examinar"))
        self.thresholdLabel.setText(_translate("MainWindow", "Umbral del modelo:"))
        self.label.setText(_translate("MainWindow", "Función de ganancia:"))
        self.gainRadioButton.setText(_translate("MainWindow", "Ganacia de información"))
        self.gainRatioRadioButton.setText(_translate("MainWindow", "Tasa de ganancia de información"))
        self.confirmButton.setText(_translate("MainWindow", "Confirmar"))
        self.discardButton.setText(_translate("MainWindow", "Descartar"))
        self.buildTreeButton.setText(_translate("MainWindow", "Construir Árbol"))
        self.classificationButton.setText(_translate("MainWindow", "Clasificar dato"))
        self.plotTreeButton.setText(_translate("MainWindow", "Graficar árbol"))
        self.plotDataButton.setText(_translate("MainWindow", "Graficar datos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

