# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(620, 533)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.configurationFrame = QtWidgets.QFrame(self.centralwidget)
        self.configurationFrame.setGeometry(QtCore.QRect(10, 10, 601, 120))
        self.configurationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.configurationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.configurationFrame.setObjectName("configurationFrame")
        self.layoutWidget_2 = QtWidgets.QWidget(self.configurationFrame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 601, 120))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.configuration = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.configuration.setContentsMargins(0, 0, 0, 0)
        self.configuration.setObjectName("configuration")
        self.titleLayout = QtWidgets.QVBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.title = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.titleLayout.addWidget(self.title)
        self.titleLine = QtWidgets.QFrame(self.layoutWidget_2)
        self.titleLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.titleLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.titleLine.setObjectName("titleLine")
        self.titleLayout.addWidget(self.titleLine)
        self.configuration.addLayout(self.titleLayout)
        self.separatorLayout = QtWidgets.QHBoxLayout()
        self.separatorLayout.setObjectName("separatorLayout")
        self.separatorLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.separatorLabel.setObjectName("separatorLabel")
        self.separatorLayout.addWidget(self.separatorLabel)
        self.separatorEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.separatorEdit.setObjectName("separatorEdit")
        self.separatorLayout.addWidget(self.separatorEdit)
        self.separatorDefaultLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.separatorDefaultLabel.setObjectName("separatorDefaultLabel")
        self.separatorLayout.addWidget(self.separatorDefaultLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.separatorLayout.addItem(spacerItem)
        self.configuration.addLayout(self.separatorLayout)
        self.lineTerminatorLayout = QtWidgets.QHBoxLayout()
        self.lineTerminatorLayout.setObjectName("lineTerminatorLayout")
        self.lineTerminatorLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.lineTerminatorLabel.setObjectName("lineTerminatorLabel")
        self.lineTerminatorLayout.addWidget(self.lineTerminatorLabel)
        self.lineTerminatorEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineTerminatorEdit.setObjectName("lineTerminatorEdit")
        self.lineTerminatorLayout.addWidget(self.lineTerminatorEdit)
        self.lineTerminatorDefaultLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.lineTerminatorDefaultLabel.setObjectName("lineTerminatorDefaultLabel")
        self.lineTerminatorLayout.addWidget(self.lineTerminatorDefaultLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lineTerminatorLayout.addItem(spacerItem1)
        self.configuration.addLayout(self.lineTerminatorLayout)
        self.testPercentajeLayout = QtWidgets.QHBoxLayout()
        self.testPercentajeLayout.setObjectName("testPercentajeLayout")
        self.testPerLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.testPerLabel.setObjectName("testPerLabel")
        self.testPercentajeLayout.addWidget(self.testPerLabel)
        self.testPerEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.testPerEdit.setObjectName("testPerEdit")
        self.testPercentajeLayout.addWidget(self.testPerEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.testPercentajeLayout.addItem(spacerItem2)
        self.configuration.addLayout(self.testPercentajeLayout)
        self.debugTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.debugTextBrowser.setGeometry(QtCore.QRect(10, 300, 599, 221))
        self.debugTextBrowser.setObjectName("debugTextBrowser")
        self.fileBrowserFrame = QtWidgets.QFrame(self.centralwidget)
        self.fileBrowserFrame.setGeometry(QtCore.QRect(10, 180, 601, 36))
        self.fileBrowserFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fileBrowserFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fileBrowserFrame.setObjectName("fileBrowserFrame")
        self.layoutWidget = QtWidgets.QWidget(self.fileBrowserFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 601, 36))
        self.layoutWidget.setObjectName("layoutWidget")
        self.fileBrowserLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.fileBrowserLayout.setContentsMargins(0, 0, 0, 0)
        self.fileBrowserLayout.setObjectName("fileBrowserLayout")
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.fileBrowserLayout.addWidget(self.line)
        self.fileBrowserLayoutH = QtWidgets.QHBoxLayout()
        self.fileBrowserLayoutH.setObjectName("fileBrowserLayoutH")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.fileBrowserLayoutH.addWidget(self.label_2)
        self.trainingLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.trainingLineEdit.setEnabled(False)
        self.trainingLineEdit.setAcceptDrops(False)
        self.trainingLineEdit.setObjectName("trainingLineEdit")
        self.fileBrowserLayoutH.addWidget(self.trainingLineEdit)
        self.browseButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseButton.sizePolicy().hasHeightForWidth())
        self.browseButton.setSizePolicy(sizePolicy)
        self.browseButton.setObjectName("browseButton")
        self.fileBrowserLayoutH.addWidget(self.browseButton)
        self.fileBrowserLayout.addLayout(self.fileBrowserLayoutH)
        self.thresholdFrame = QtWidgets.QFrame(self.centralwidget)
        self.thresholdFrame.setGeometry(QtCore.QRect(10, 230, 601, 22))
        self.thresholdFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.thresholdFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.thresholdFrame.setObjectName("thresholdFrame")
        self.widget = QtWidgets.QWidget(self.thresholdFrame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 601, 22))
        self.widget.setObjectName("widget")
        self.thresholdLayout = QtWidgets.QHBoxLayout(self.widget)
        self.thresholdLayout.setContentsMargins(0, 0, 0, 0)
        self.thresholdLayout.setObjectName("thresholdLayout")
        self.thresholdLabel = QtWidgets.QLabel(self.widget)
        self.thresholdLabel.setObjectName("thresholdLabel")
        self.thresholdLayout.addWidget(self.thresholdLabel)
        self.thresholdEdit = QtWidgets.QLineEdit(self.widget)
        self.thresholdEdit.setObjectName("thresholdEdit")
        self.thresholdLayout.addWidget(self.thresholdEdit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.thresholdLayout.addItem(spacerItem3)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 140, 601, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.confirmButtonLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.confirmButtonLayout.setContentsMargins(0, 0, 0, 0)
        self.confirmButtonLayout.setObjectName("confirmButtonLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.confirmButtonLayout.addItem(spacerItem4)
        self.confirmButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.confirmButton.setObjectName("confirmButton")
        self.confirmButtonLayout.addWidget(self.confirmButton)
        self.discardButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.discardButton.setObjectName("discardButton")
        self.confirmButtonLayout.addWidget(self.discardButton)
        self.classifyFrame = QtWidgets.QFrame(self.centralwidget)
        self.classifyFrame.setGeometry(QtCore.QRect(10, 260, 601, 25))
        self.classifyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.classifyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.classifyFrame.setObjectName("classifyFrame")
        self.widget1 = QtWidgets.QWidget(self.classifyFrame)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 601, 25))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.classifyButton = QtWidgets.QPushButton(self.widget1)
        self.classifyButton.setEnabled(True)
        self.classifyButton.setObjectName("classifyButton")
        self.horizontalLayout.addWidget(self.classifyButton)
        self.configurationFrame.raise_()
        self.debugTextBrowser.raise_()
        self.fileBrowserFrame.raise_()
        self.thresholdFrame.raise_()
        self.thresholdLabel.raise_()
        self.thresholdEdit.raise_()
        self.layoutWidget.raise_()
        self.classifyButton.raise_()
        self.classifyFrame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Importación"))
        self.separatorLabel.setText(_translate("MainWindow", "Separador de campos:"))
        self.separatorDefaultLabel.setText(_translate("MainWindow", "(por defecto \',\')"))
        self.lineTerminatorLabel.setText(_translate("MainWindow", "Delimitador de fila:"))
        self.lineTerminatorDefaultLabel.setText(_translate("MainWindow", "(por defecto \'salto de línea\')"))
        self.testPerLabel.setText(_translate("MainWindow", "Porcentaje de datos para prueba:"))
        self.label_2.setText(_translate("MainWindow", "Archivo:"))
        self.browseButton.setText(_translate("MainWindow", "Examinar"))
        self.thresholdLabel.setText(_translate("MainWindow", "Umbral del modelo:"))
        self.confirmButton.setText(_translate("MainWindow", "Confirmar"))
        self.discardButton.setText(_translate("MainWindow", "Descartar"))
        self.classifyButton.setText(_translate("MainWindow", "Clasificar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

