# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(620, 533)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.configurationFrame = QtWidgets.QFrame(self.centralwidget)
        self.configurationFrame.setGeometry(QtCore.QRect(10, 10, 601, 141))
        self.configurationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.configurationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.configurationFrame.setObjectName("configurationFrame")
        self.layoutWidget_2 = QtWidgets.QWidget(self.configurationFrame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 601, 131))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.configuration = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.configuration.setContentsMargins(0, 0, 0, 0)
        self.configuration.setObjectName("configuration")
        self.titleLayout = QtWidgets.QVBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.title = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.titleLayout.addWidget(self.title)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.titleLayout.addWidget(self.line_2)
        self.configuration.addLayout(self.titleLayout)
        self.separatorLayout = QtWidgets.QHBoxLayout()
        self.separatorLayout.setObjectName("separatorLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.separatorLayout.addWidget(self.label_4)
        self.separator = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.separator.setObjectName("separator")
        self.separatorLayout.addWidget(self.separator)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.separatorLayout.addWidget(self.label_7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.separatorLayout.addItem(spacerItem)
        self.configuration.addLayout(self.separatorLayout)
        self.lineTerminatorLayout = QtWidgets.QHBoxLayout()
        self.lineTerminatorLayout.setObjectName("lineTerminatorLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.lineTerminatorLayout.addWidget(self.label_5)
        self.lineTerminator = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineTerminator.setObjectName("lineTerminator")
        self.lineTerminatorLayout.addWidget(self.lineTerminator)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.lineTerminatorLayout.addWidget(self.label_8)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lineTerminatorLayout.addItem(spacerItem1)
        self.configuration.addLayout(self.lineTerminatorLayout)
        self.testPercentajeLayout = QtWidgets.QHBoxLayout()
        self.testPercentajeLayout.setObjectName("testPercentajeLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.testPercentajeLayout.addWidget(self.label_6)
        self.testPer = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.testPer.setObjectName("testPer")
        self.testPercentajeLayout.addWidget(self.testPer)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.testPercentajeLayout.addItem(spacerItem2)
        self.configuration.addLayout(self.testPercentajeLayout)
        self.debugTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.debugTextBrowser.setGeometry(QtCore.QRect(10, 260, 599, 261))
        self.debugTextBrowser.setObjectName("debugTextBrowser")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 150, 601, 25))
        self.widget.setObjectName("widget")
        self.confirmButtonLayout = QtWidgets.QHBoxLayout(self.widget)
        self.confirmButtonLayout.setContentsMargins(0, 0, 0, 0)
        self.confirmButtonLayout.setObjectName("confirmButtonLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.confirmButtonLayout.addItem(spacerItem3)
        self.confirmButton = QtWidgets.QPushButton(self.widget)
        self.confirmButton.setObjectName("confirmButton")
        self.confirmButtonLayout.addWidget(self.confirmButton)
        self.discardButton = QtWidgets.QPushButton(self.widget)
        self.discardButton.setObjectName("discardButton")
        self.confirmButtonLayout.addWidget(self.discardButton)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 210, 601, 36))
        self.widget1.setObjectName("widget1")
        self.fileBrowserLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.fileBrowserLayout.setContentsMargins(0, 0, 0, 0)
        self.fileBrowserLayout.setObjectName("fileBrowserLayout")
        self.line = QtWidgets.QFrame(self.widget1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.fileBrowserLayout.addWidget(self.line)
        self.fileBrowserLayoutH = QtWidgets.QHBoxLayout()
        self.fileBrowserLayoutH.setObjectName("fileBrowserLayoutH")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.fileBrowserLayoutH.addWidget(self.label_2)
        self.trainingLineEdit = QtWidgets.QLineEdit(self.widget1)
        self.trainingLineEdit.setEnabled(False)
        self.trainingLineEdit.setAcceptDrops(False)
        self.trainingLineEdit.setObjectName("trainingLineEdit")
        self.fileBrowserLayoutH.addWidget(self.trainingLineEdit)
        self.browseButton = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseButton.sizePolicy().hasHeightForWidth())
        self.browseButton.setSizePolicy(sizePolicy)
        self.browseButton.setObjectName("browseButton")
        self.fileBrowserLayoutH.addWidget(self.browseButton)
        self.classifyButton = QtWidgets.QPushButton(self.widget1)
        self.classifyButton.setEnabled(False)
        self.classifyButton.setObjectName("classifyButton")
        self.fileBrowserLayoutH.addWidget(self.classifyButton)
        self.fileBrowserLayout.addLayout(self.fileBrowserLayoutH)
        self.configurationFrame.raise_()
        self.debugTextBrowser.raise_()
        self.line.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Importación"))
        self.label_4.setText(_translate("MainWindow", "Separador de campos:"))
        self.label_7.setText(_translate("MainWindow", "(por defecto \',\')"))
        self.label_5.setText(_translate("MainWindow", "Delimitador de fila:"))
        self.label_8.setText(_translate("MainWindow", "(por defecto \'salto de línea\')"))
        self.label_6.setText(_translate("MainWindow", "Porcentaje de datos para prueba:"))
        self.confirmButton.setText(_translate("MainWindow", "Confirmar"))
        self.discardButton.setText(_translate("MainWindow", "Descartar"))
        self.label_2.setText(_translate("MainWindow", "Archivo:"))
        self.browseButton.setText(_translate("MainWindow", "Examinar"))
        self.classifyButton.setText(_translate("MainWindow", "Clasificar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

